### PR TITLE
Added readme on how to use snabbdom-tsx

### PR DESCRIPTION
**Pull request by mhgamework**
Hey, this library is awesome for use with cycle.js. I created this readme on how i started using it and I think it would be awesome if you would add it to the repository.

Greetz

MH

### CODE REVIEW

**Comment by Swizz** [comment]
Hi, I worked on a pretty similar solution (I am happy to see we go to the same direction). 

But, I aim to be JSX capable transpiler independent. 

What about merging our strength ? Take a look at [Swizz/Snabbdom-pragma](http://github.com/Swizz/Snabbdom-pragma)

**Comment by alvivi** [comment]
Hi guys, I'm not using Snabbdom (nor cycle.js) anymore. So feel free to fork or take from here whatever you want. 👍

**Comment by mhgamework** [comment]
What was your reason for leaving cycle?

**Comment by alvivi** [comment]
@mhgamework, In the end, I was using lots of libraries to build projects in a functional way (like cycle, [immutable.js](https://facebook.github.io/immutable-js/), [fantasyland](https://github.com/fantasyland/fantasy-land) and so on). So I moved to functional languages targeting the web platform: [Elm](http://elm-lang.org/), [PureScript](http://www.purescript.org/), [Reason](https://facebook.github.io/reason/). Also, I think that [onionfy](https://github.com/staltz/cycle-onionify) seems like an overengineered fix to some of the cycle.js problems (imho). Anyway, I'm still thinking that cycle is one the best js frameworks out there.

**Comment by mhgamework** [comment]
I definitely agree that the highly functional style of cycle quickly clashes with the imperative mindset of JS/TS. Do you have any alternative view/model frameworks that you use then in Purescript or Reason? (I guess in Elm you would just use the elm architecture?)

**Comment by Swizz** [comment]
Isn't Reason and Cyclejs compatible ?

I always Thought that Reason allows the use of JS lib, I may be wrong.

**Comment by alvivi** [comment]
@mhgamework You are right about *Elm*, is a "battery-included" language for web apps (even more in the next version (Code Slicing, Server-Side Rendering and Lazy Loading). Its "framework" is soft-reactive, so is very easy to use the whole language. If you try to do something more complex, elm is going to be like a wall, languages like purescript and reason are a better option. In purescript, you have [pux](http://purescript-pux.org/), which follows the same approach than Elm. Other options are [flare](https://github.com/sharkdp/purescript-flare), similar to cycle.js and [halogen](https://github.com/slamdata/purescript-halogen), too hardcore for newcomers. Just try elm, if you like cycle, you are going to like elm too :+1:

@Swizz Of course, you can use cycle.js from Reason and Purescript (not elm). In purescript maybe it makes not sense when you already have other viable options. The reason/ocalmjs ecosystem is smaller than the others, so yes, maybe you can write a wrapper to use cycle.js.

**Pull request merged**
